# /etc/xdg/reflector/reflector.conf
# Configuração do reflector para PeachOS
# Atualizado semanalmente pelo reflector.timer

--country Brazil
--latest 10
--sort rate
--protocol https
--save /etc/pacman.d/mirrorlist
